### ISSUE TITLE
SecretsManager + IKS - yaml for installation of helm chart with a trusted profile errors

### ISSUE THREAD

**Issue by isaaceichelberger** [ibm-cloud-docs/secrets-manager#19]
Docs link: https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-tutorial-kubernetes-secrets
When running
```bash
echo '
installCRDs: true
extraVolumes:
- name: sa-token
projected:
    defaultMode: 420
    sources:
    - serviceAccountToken:
        path: sa-token
        expirationSeconds: 3600
        audience: iam
extraVolumeMounts:
- mountPath: /var/run/secrets/tokens
name: sa-token
webhook:
  extraVolumes:
  - name: sa-token
      projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          path: sa-token
          expirationSeconds: 3600
          audience: iam
  extraVolumeMounts:
  - mountPath: /var/run/secrets/tokens
      name: sa-token' >values.yml
helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace -f values.yml
``` 
as mentioned by the docs, you will get this error

```
Error: INSTALLATION FAILED: failed to parse values.yml: error converting YAML to JSON: yaml: line 18: mapping values are not allowed in this context
```

The yaml file should be as follows:
```yaml

installCRDs: true
extraVolumes:
- name: sa-token
projected:
    defaultMode: 420
    sources:
    - serviceAccountToken:
        path: sa-token
        expirationSeconds: 3600
        audience: iam
extraVolumeMounts:
- mountPath: /var/run/secrets/tokens
name: sa-token
webhook:
  extraVolumes:
  - name: sa-token
      projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          path: sa-token
          expirationSeconds: 3600
          audience: iam
  extraVolumeMounts:
  - mountPath: /var/run/secrets/tokens
      name: sa-token
```
